<?php
$html = file_get_contents(__DIR__ . '/index.html');
$css = <<<'CSS'
<style>
.hero{position:relative;overflow:hidden;grid-template-columns:minmax(0,1.05fr) minmax(380px,.95fr);gap:36px}
.hero-copy{position:relative;z-index:2}.hero-visual{position:relative;z-index:2;min-height:520px;display:grid;grid-template-columns:1.08fr .92fr;grid-template-rows:1fr 1fr;gap:14px}.hero-shot{position:relative;overflow:hidden;border-radius:24px;border:1px solid rgba(255,255,255,.18);background:#fff;box-shadow:0 28px 70px rgba(0,0,0,.3)}.hero-shot.big{grid-row:1/3}.hero-shot img{width:100%;height:100%;object-fit:contain;padding:18px;display:block;background:#fff}.hero-shot .label{position:absolute;left:14px;bottom:14px;padding:8px 11px;border-radius:999px;background:#351457;color:#ffd43b;font-size:11px;font-weight:900;letter-spacing:.06em;box-shadow:0 8px 25px #0005}.featured-strip{padding:34px 6vw 48px;background:#0d0711}.featured-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.featured-card{display:block;text-decoration:none;border:1px solid #ffffff17;background:#160d1d;border-radius:18px;overflow:hidden}.featured-card img{width:100%;height:180px;object-fit:contain;background:#fff;padding:12px;display:block}.featured-card div{padding:12px 14px;font-weight:900;font-size:13px}.featured-card small{display:block;color:#ab97b5;margin-top:4px;font-weight:600}.featured-card:hover{transform:translateY(-2px);border-color:#ffd43b66}.front-note{margin:0 0 14px;color:#b9a7c2;font-size:13px}.hero:before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(17,8,24,.97) 0%,rgba(17,8,24,.9) 42%,rgba(17,8,24,.28) 72%,rgba(17,8,24,.08) 100%);z-index:1;pointer-events:none}@media(max-width:1000px){.hero{grid-template-columns:1fr}.hero-visual{min-height:420px}.featured-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.hero-visual{grid-template-columns:1fr 1fr;min-height:360px}.featured-grid{grid-template-columns:1fr 1fr}.featured-card img{height:140px}}
</style>
CSS;
$html = str_replace('</head>', $css . '</head>', $html);
$old = '<section class="hero"><div><span class="tag">TUBS OF FUN • FLAGSHIP ATTRACTION</span>';
$new = '<section class="hero"><div class="hero-copy"><span class="tag">TUBS OF FUN • FLAGSHIP ATTRACTION</span>';
$html = str_replace($old, $new, $html);
$heroEnd = '<a class="cta" href="#booking">BOOK YOUR EVENT →</a></div></section><div class="stats">';
$heroVisual = '<a class="cta" href="#booking">BOOK YOUR EVENT →</a></div><div class="hero-visual" aria-label="Featured Party Tyme attractions"><a class="hero-shot big" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/A85F18EA-6BBB-4011-B239-C6AB6A9E4303_1771948423.png" alt="Party Tyme Bumper Cars"><span class="label">BUMPER CARS</span></a><a class="hero-shot" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/holiday-trackless-train-rental-party-tyme-amusements_1772052295.png" alt="Party Tyme Holiday Trackless Train"><span class="label">HOLIDAY TRAIN</span></a><a class="hero-shot" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/images-3_1691177056.jpeg" alt="Party Tyme Twin Spin Ride"><span class="label">TWIN SPIN</span></a></div></section><section class="featured-strip"><p class="front-note">Featured Party Tyme attractions pulled from the current Party Tyme rental catalog.</p><div class="featured-grid"><a class="featured-card" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/A85F18EA-6BBB-4011-B239-C6AB6A9E4303_1771948423.png" alt="Bumper Cars"><div>Bumper Cars<small>Flagship midway attraction</small></div></a><a class="featured-card" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/85ft-inflatable-zip-line-rental-party-tyme_1771950729.png" alt="85 foot Inflatable Zip Line"><div>85&#39; Inflatable Zip Line<small>High-impact festival attraction</small></div></a><a class="featured-card" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/7D33DE64-3294-4C1A-8593-F5AF73FADB55_1771949168.png" alt="Mechanical Bull"><div>Mechanical Bull<small>Popular interactive ride</small></div></a><a class="featured-card" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/holiday-trackless-train-rental-party-tyme-amusements_1772052295.png" alt="Holiday Trackless Train"><div>Holiday Trackless Train<small>Seasonal event favourite</small></div></a><a class="featured-card" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/images-3_1691177056.jpeg" alt="Twin Spin Ride"><div>Twin Spin Ride<small>Spinning amusement attraction</small></div></a></div></section><div class="stats">';
$html = str_replace($heroEnd, $heroVisual, $html);
echo $html;
?>