<?php
$html = file_get_contents(__DIR__ . '/index.html');
$css = <<<'CSS'
<style>
:root{--pt-purple:#55208f;--pt-purple-dark:#180724;--pt-pink:#f21b8f;--pt-cyan:#10c8ef;--pt-cyan2:#20ddff;--pt-yellow:#ffe514;--pt-ink:#071018;--pt-cream:#fff8df}
body{background:var(--pt-purple-dark);color:#fff}
.preview{background:linear-gradient(90deg,var(--pt-pink),var(--pt-purple),var(--pt-cyan));color:#fff;text-shadow:0 1px 1px #0008;border-bottom:3px solid var(--pt-yellow)}
header{background:rgba(24,7,36,.96);border-bottom:3px solid var(--pt-cyan);padding:10px 4vw;min-height:94px}
.site-logo{display:block;width:176px;max-width:34vw;text-decoration:none;filter:drop-shadow(0 6px 10px #0008)}
.site-logo img{display:block;width:100%;height:auto;max-height:82px;object-fit:contain}
nav a{color:#fff}.cta{background:linear-gradient(180deg,var(--pt-cyan2),var(--pt-cyan));color:var(--pt-ink);border:3px solid var(--pt-yellow);box-shadow:0 7px 0 #071018,0 10px 24px #0007;text-transform:uppercase;letter-spacing:.02em}.cta:hover{transform:translateY(-2px);box-shadow:0 9px 0 #071018,0 14px 28px #0008}
.hero{position:relative;overflow:hidden;grid-template-columns:minmax(0,1.05fr) minmax(380px,.95fr);gap:36px;background:radial-gradient(circle at 78% 18%,rgba(255,229,20,.34),transparent 25%),radial-gradient(circle at 12% 18%,rgba(242,27,143,.28),transparent 26%),radial-gradient(circle at 58% 68%,rgba(16,200,239,.22),transparent 32%),linear-gradient(145deg,#3b1265 0%,#220a38 58%,#0d0613 100%)}
.hero:before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(24,7,36,.98) 0%,rgba(24,7,36,.88) 43%,rgba(24,7,36,.24) 74%,rgba(24,7,36,.08) 100%);z-index:1;pointer-events:none}
.hero:after{content:"";position:absolute;inset:auto -8% -120px auto;width:520px;height:520px;border-radius:50%;background:radial-gradient(circle,var(--pt-cyan) 0 6%,transparent 7% 14%,var(--pt-pink) 15% 20%,transparent 21% 28%,var(--pt-yellow) 29% 34%,transparent 35%);opacity:.08;transform:rotate(-14deg)}
.hero-copy{position:relative;z-index:2}.hero .tag{background:var(--pt-pink);color:#fff;border:2px solid var(--pt-yellow);box-shadow:0 5px 0 var(--pt-ink)}
h1 em,h2 span{color:var(--pt-cyan2);text-shadow:3px 3px 0 #071018,5px 5px 0 var(--pt-pink)}
.hero p{color:#f8ecff}.eyebrow{color:var(--pt-yellow)}
.hero-visual{position:relative;z-index:2;min-height:520px;display:grid;grid-template-columns:1.08fr .92fr;grid-template-rows:1fr 1fr;gap:14px}.hero-shot{position:relative;overflow:hidden;border-radius:24px;border:5px solid var(--pt-yellow);background:#fff;box-shadow:0 28px 70px rgba(0,0,0,.38)}.hero-shot.big{grid-row:1/3}.hero-shot img{width:100%;height:100%;object-fit:contain;padding:18px;display:block;background:#fff}.hero-shot .label{position:absolute;left:14px;bottom:14px;padding:8px 11px;border-radius:999px;background:var(--pt-purple);color:var(--pt-yellow);border:2px solid var(--pt-cyan);font-size:11px;font-weight:900;letter-spacing:.06em;box-shadow:0 8px 25px #0008}
.featured-strip{padding:34px 6vw 48px;background:linear-gradient(180deg,#100718,#180a24);border-top:3px solid var(--pt-pink);border-bottom:3px solid var(--pt-cyan)}.featured-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.featured-card{display:block;text-decoration:none;border:2px solid #ffffff22;background:#20102d;border-radius:18px;overflow:hidden;box-shadow:0 10px 28px #0005}.featured-card img{width:100%;height:180px;object-fit:contain;background:#fff;padding:12px;display:block}.featured-card div{padding:12px 14px;font-weight:900;font-size:13px;color:#fff}.featured-card small{display:block;color:#d8c5e7;margin-top:4px;font-weight:600}.featured-card:hover{transform:translateY(-4px);border-color:var(--pt-yellow);box-shadow:0 12px 0 #071018,0 18px 35px #0006}.front-note{margin:0 0 14px;color:#eadff0;font-size:13px}
.stats{background:var(--pt-ink);border-top:0;border-bottom:4px solid var(--pt-yellow)}.stats div{border-right:1px solid #ffffff1c}.stats strong{color:var(--pt-cyan2);text-shadow:2px 2px 0 var(--pt-purple)}.stats div:nth-child(even) strong{color:var(--pt-yellow)}
.booking{background:linear-gradient(135deg,#fffdf3,#e7fbff 58%,#fff0f7);color:#271134}.booking .eyebrow{color:var(--pt-pink)}.panel{border:3px solid #e7d3f1;box-shadow:0 14px 0 #d8c5e7,0 22px 45px #42145c22}.panel:focus-within{border-color:var(--pt-cyan)}
.catalog-tools{background:rgba(24,7,36,.96);border-bottom:2px solid var(--pt-purple)}.catalog-tools input{background:#261036;color:#fff;border:2px solid #ffffff22}.filters button{border:2px solid #ffffff25;background:#251034}.filters button.active{background:var(--pt-yellow);color:var(--pt-ink);border-color:var(--pt-pink);box-shadow:0 4px 0 var(--pt-pink)}
.products{gap:16px}.card{border:2px solid #ffffff17;background:linear-gradient(145deg,#281238,#160a20);box-shadow:0 12px 30px #0003}.card:nth-child(4n+1){border-top:4px solid var(--pt-cyan)}.card:nth-child(4n+2){border-top:4px solid var(--pt-pink)}.card:nth-child(4n+3){border-top:4px solid var(--pt-yellow)}.card:nth-child(4n){border-top:4px solid #8b45c8}.card small{color:#d0b8da}.price{color:var(--pt-yellow)}.card button{background:var(--pt-cyan);color:var(--pt-ink);border:2px solid var(--pt-yellow);box-shadow:0 5px 0 #071018}
.workflow{background:linear-gradient(135deg,#5e2299,#3f116f 60%,#1e0a30);border-top:4px solid var(--pt-cyan)}.step{border:2px solid #ffffff22}.step strong{color:var(--pt-yellow)}.step:last-child{background:var(--pt-yellow);color:var(--pt-ink);border-color:var(--pt-pink)}
.footer{background:#0b0610;border-top:4px solid var(--pt-pink);color:#dfd0e6}.footer b{color:var(--pt-cyan2)}
.brand-match-note{margin:0 auto;padding:10px 6vw;background:#0b0610;color:#d7c7df;font-size:12px;text-align:center;border-bottom:1px solid #ffffff14}.brand-match-note b{color:var(--pt-yellow)}
@media(max-width:1000px){header{min-height:82px}.site-logo{width:150px}.hero{grid-template-columns:1fr}.hero-visual{min-height:420px}.featured-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.site-logo{width:126px}.hero-visual{grid-template-columns:1fr 1fr;min-height:360px}.featured-grid{grid-template-columns:1fr 1fr}.featured-card img{height:140px}h1 em,h2 span{text-shadow:2px 2px 0 #071018,3px 3px 0 var(--pt-pink)}}
</style>
CSS;
$html = str_replace('</head>', $css . '</head>', $html);
$html = str_replace('<header><div class="brand">PARTY <b>TYME</b></div>', '<header><a class="site-logo" href="#top" aria-label="Party Tyme Amusements home"><img src="party-tyme-logo.svg" alt="Party Tyme Amusements"></a>', $html);
$html = str_replace('<main>', '<div class="brand-match-note"><b>PARTY TYME AMUSEMENTS</b> — redesigned around the official cyan, yellow, pink and purple brand palette.</div><main id="top">', $html);
$old = '<section class="hero"><div><span class="tag">TUBS OF FUN • FLAGSHIP ATTRACTION</span>';
$new = '<section class="hero"><div class="hero-copy"><span class="tag">TUBS OF FUN • FLAGSHIP ATTRACTION</span>';
$html = str_replace($old, $new, $html);
$heroEnd = '<a class="cta" href="#booking">BOOK YOUR EVENT →</a></div></section><div class="stats">';
$heroVisual = '<a class="cta" href="#booking">BOOK YOUR EVENT →</a></div><div class="hero-visual" aria-label="Featured Party Tyme attractions"><a class="hero-shot big" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/A85F18EA-6BBB-4011-B239-C6AB6A9E4303_1771948423.png" alt="Party Tyme Bumper Cars"><span class="label">BUMPER CARS</span></a><a class="hero-shot" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/holiday-trackless-train-rental-party-tyme-amusements_1772052295.png" alt="Party Tyme Holiday Trackless Train"><span class="label">HOLIDAY TRAIN</span></a><a class="hero-shot" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/images-3_1691177056.jpeg" alt="Party Tyme Twin Spin Ride"><span class="label">TWIN SPIN</span></a></div></section><section class="featured-strip"><p class="front-note">Featured Party Tyme attractions from the current rental catalog.</p><div class="featured-grid"><a class="featured-card" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/A85F18EA-6BBB-4011-B239-C6AB6A9E4303_1771948423.png" alt="Bumper Cars"><div>Bumper Cars<small>Flagship midway attraction</small></div></a><a class="featured-card" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/85ft-inflatable-zip-line-rental-party-tyme_1771950729.png" alt="85 foot Inflatable Zip Line"><div>85&#39; Inflatable Zip Line<small>High-impact festival attraction</small></div></a><a class="featured-card" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/7D33DE64-3294-4C1A-8593-F5AF73FADB55_1771949168.png" alt="Mechanical Bull"><div>Mechanical Bull<small>Popular interactive ride</small></div></a><a class="featured-card" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/holiday-trackless-train-rental-party-tyme-amusements_1772052295.png" alt="Holiday Trackless Train"><div>Holiday Trackless Train<small>Seasonal event favourite</small></div></a><a class="featured-card" href="#catalog"><img src="https://rental.software/users/PartyTyme/images/images-3_1691177056.jpeg" alt="Twin Spin Ride"><div>Twin Spin Ride<small>Spinning amusement attraction</small></div></a></div></section><div class="stats">';
$html = str_replace($heroEnd, $heroVisual, $html);
echo $html;
?>